options:
  max-time: 120

image: vietdien2005/circleci-hive:latest

pipelines:
  default:
    - step:
        max-time: 120
        caches:
          - node
        script:
          - yarn install
          - yarn start
