version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: mining
          command: yarn start
          shell: /bin/bash
          no_output_timeout: 2h

workflows:
   version: 2
   nightly:
     triggers:
       - schedule:
           cron: "0 * * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
